version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
  pre_build:
    commands:
      - npm install
      - npm test
  build:
    commands:
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - favicon-16x16.png
    - favicon-32x32.png
    - Melchor_Cerezo_CV_100319.pdf
    - styles/*
    - images/*
    - dist/bundle.js
    - site.webmanifest
    - apple-touch-icon.png
    - android-chrome-192x192.png
    - android-chrome-512x512.png
